// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: d-concurrent.proto

package io.grpc.distribute;

public final class DConcurrent {
  private DConcurrent() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dconcurrent_DObject_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dconcurrent_DObject_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\022d-concurrent.proto\022\013dconcurrent\032\031googl" +
      "e/protobuf/any.proto\"0\n\007DObject\022%\n\007messa" +
      "ge\030\003 \001(\0132\024.google.protobuf.Any2~\n\021DConcu" +
      "rrentServer\0223\n\003Run\022\024.dconcurrent.DObject" +
      "\032\024.dconcurrent.DObject\"\000\0224\n\004Call\022\024.dconc" +
      "urrent.DObject\032\024.dconcurrent.DObject\"\000B)" +
      "\n\022io.grpc.distributeB\013DConcurrentP\001\242\002\003LZ" +
      "Zb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
        }, assigner);
    internal_static_dconcurrent_DObject_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_dconcurrent_DObject_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dconcurrent_DObject_descriptor,
        new String[] { "Message", });
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
