// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: d-concurrent.proto

package io.grpc.distribute;

public final class DConcurrent {
  private DConcurrent() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dconcurrent_DObject_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dconcurrent_DObject_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\022d-concurrent.proto\022\013dconcurrent\032\031googl" +
      "e/protobuf/any.proto\"\211\001\n\007DObject\022\'\n\tclas" +
      "sName\030\001 \001(\0132\024.google.protobuf.Any\022\'\n\tmet" +
      "aParam\030\002 \001(\0132\024.google.protobuf.Any\022,\n\016me" +
      "taParamClass\030\003 \001(\0132\024.google.protobuf.Any" +
      "2~\n\021DConcurrentServer\0223\n\003Run\022\024.dconcurre" +
      "nt.DObject\032\024.dconcurrent.DObject\"\000\0224\n\004Ca" +
      "ll\022\024.dconcurrent.DObject\032\024.dconcurrent.D" +
      "Object\"\000B)\n\022io.grpc.distributeB\013DConcurr" +
      "entP\001\242\002\003LZZb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
        }, assigner);
    internal_static_dconcurrent_DObject_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_dconcurrent_DObject_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dconcurrent_DObject_descriptor,
        new String[] { "ClassName", "MetaParam", "MetaParamClass", });
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
