// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: d-concurrent.proto

package io.grpc.distribute;

public interface DObjectOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dconcurrent.DObject)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.google.protobuf.Any message = 3;</code>
   */
  boolean hasMessage();
  /**
   * <code>.google.protobuf.Any message = 3;</code>
   */
  com.google.protobuf.Any getMessage();
  /**
   * <code>.google.protobuf.Any message = 3;</code>
   */
  com.google.protobuf.AnyOrBuilder getMessageOrBuilder();
}
