// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: d-concurrent.proto

package util.dconcurrent.core;

public interface DBytesOrBuilder
    extends com.google.protobuf.MessageOrBuilder {

  // optional bytes res = 1;
  /**
   * <code>optional bytes res = 1;</code>
   */
  boolean hasRes();
  /**
   * <code>optional bytes res = 1;</code>
   */
  com.google.protobuf.ByteString getRes();
}
