// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: d-concurrent.proto

package util.dconcurrent.core;

/**
 * Protobuf type {@code dconcurrent.DBytes}
 */
public  final class DBytes extends
    com.google.protobuf.GeneratedMessage
    implements DBytesOrBuilder {
  // Use DBytes.newBuilder() to construct.
  private DBytes(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private DBytes(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final DBytes defaultInstance;
  public static DBytes getDefaultInstance() {
    return defaultInstance;
  }

  public DBytes getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private DBytes(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            bitField0_ |= 0x00000001;
            res_ = input.readBytes();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return util.dconcurrent.core.DConcurrent.internal_static_dconcurrent_DBytes_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return util.dconcurrent.core.DConcurrent.internal_static_dconcurrent_DBytes_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            util.dconcurrent.core.DBytes.class, util.dconcurrent.core.DBytes.Builder.class);
  }

  public static com.google.protobuf.Parser<DBytes> PARSER =
      new com.google.protobuf.AbstractParser<DBytes>() {
    public DBytes parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new DBytes(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public com.google.protobuf.Parser<DBytes> getParserForType() {
    return PARSER;
  }

  private int bitField0_;
  // optional bytes res = 1;
  public static final int RES_FIELD_NUMBER = 1;
  private com.google.protobuf.ByteString res_;
  /**
   * <code>optional bytes res = 1;</code>
   */
  public boolean hasRes() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>optional bytes res = 1;</code>
   */
  public com.google.protobuf.ByteString getRes() {
    return res_;
  }

  private void initFields() {
    res_ = com.google.protobuf.ByteString.EMPTY;
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized != -1) return isInitialized == 1;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeBytes(1, res_);
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, res_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  public static util.dconcurrent.core.DBytes parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static util.dconcurrent.core.DBytes parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static util.dconcurrent.core.DBytes parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static util.dconcurrent.core.DBytes parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static util.dconcurrent.core.DBytes parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static util.dconcurrent.core.DBytes parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static util.dconcurrent.core.DBytes parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static util.dconcurrent.core.DBytes parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static util.dconcurrent.core.DBytes parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static util.dconcurrent.core.DBytes parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(util.dconcurrent.core.DBytes prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code dconcurrent.DBytes}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder>
     implements util.dconcurrent.core.DBytesOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return util.dconcurrent.core.DConcurrent.internal_static_dconcurrent_DBytes_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return util.dconcurrent.core.DConcurrent.internal_static_dconcurrent_DBytes_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              util.dconcurrent.core.DBytes.class, util.dconcurrent.core.DBytes.Builder.class);
    }

    // Construct using util.dconcurrent.core.DBytes.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      res_ = com.google.protobuf.ByteString.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return util.dconcurrent.core.DConcurrent.internal_static_dconcurrent_DBytes_descriptor;
    }

    public util.dconcurrent.core.DBytes getDefaultInstanceForType() {
      return util.dconcurrent.core.DBytes.getDefaultInstance();
    }

    public util.dconcurrent.core.DBytes build() {
      util.dconcurrent.core.DBytes result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public util.dconcurrent.core.DBytes buildPartial() {
      util.dconcurrent.core.DBytes result = new util.dconcurrent.core.DBytes(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.res_ = res_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof util.dconcurrent.core.DBytes) {
        return mergeFrom((util.dconcurrent.core.DBytes)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(util.dconcurrent.core.DBytes other) {
      if (other == util.dconcurrent.core.DBytes.getDefaultInstance()) return this;
      if (other.hasRes()) {
        setRes(other.getRes());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      util.dconcurrent.core.DBytes parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (util.dconcurrent.core.DBytes) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    // optional bytes res = 1;
    private com.google.protobuf.ByteString res_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>optional bytes res = 1;</code>
     */
    public boolean hasRes() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional bytes res = 1;</code>
     */
    public com.google.protobuf.ByteString getRes() {
      return res_;
    }
    /**
     * <code>optional bytes res = 1;</code>
     */
    public Builder setRes(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      res_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bytes res = 1;</code>
     */
    public Builder clearRes() {
      bitField0_ = (bitField0_ & ~0x00000001);
      res_ = getDefaultInstance().getRes();
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:dconcurrent.DBytes)
  }

  static {
    defaultInstance = new DBytes(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:dconcurrent.DBytes)
}

