// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: d-concurrent.proto

package util.dconcurrent.core;

/**
 * Protobuf type {@code dconcurrent.DObject}
 */
public  final class DObject extends
    com.google.protobuf.GeneratedMessage
    implements util.dconcurrent.core.DObjectOrBuilder {
  // Use DObject.newBuilder() to construct.
  private DObject(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private DObject(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final DObject defaultInstance;
  public static DObject getDefaultInstance() {
    return defaultInstance;
  }

  public DObject getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private DObject(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            bitField0_ |= 0x00000001;
            className_ = input.readBytes();
            break;
          }
          case 18: {
            bitField0_ |= 0x00000002;
            metaParam_ = input.readBytes();
            break;
          }
          case 26: {
            bitField0_ |= 0x00000004;
            metaParamClass_ = input.readBytes();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return util.dconcurrent.core.DConcurrent.internal_static_dconcurrent_DObject_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return util.dconcurrent.core.DConcurrent.internal_static_dconcurrent_DObject_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            util.dconcurrent.core.DObject.class, util.dconcurrent.core.DObject.Builder.class);
  }

  public static com.google.protobuf.Parser<DObject> PARSER =
      new com.google.protobuf.AbstractParser<DObject>() {
    public DObject parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new DObject(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public com.google.protobuf.Parser<DObject> getParserForType() {
    return PARSER;
  }

  private int bitField0_;
  // optional bytes className = 1;
  public static final int CLASSNAME_FIELD_NUMBER = 1;
  private com.google.protobuf.ByteString className_;
  /**
   * <code>optional bytes className = 1;</code>
   */
  public boolean hasClassName() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>optional bytes className = 1;</code>
   */
  public com.google.protobuf.ByteString getClassName() {
    return className_;
  }

  // optional bytes metaParam = 2;
  public static final int METAPARAM_FIELD_NUMBER = 2;
  private com.google.protobuf.ByteString metaParam_;
  /**
   * <code>optional bytes metaParam = 2;</code>
   */
  public boolean hasMetaParam() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>optional bytes metaParam = 2;</code>
   */
  public com.google.protobuf.ByteString getMetaParam() {
    return metaParam_;
  }

  // optional bytes metaParamClass = 3;
  public static final int METAPARAMCLASS_FIELD_NUMBER = 3;
  private com.google.protobuf.ByteString metaParamClass_;
  /**
   * <code>optional bytes metaParamClass = 3;</code>
   */
  public boolean hasMetaParamClass() {
    return ((bitField0_ & 0x00000004) == 0x00000004);
  }
  /**
   * <code>optional bytes metaParamClass = 3;</code>
   */
  public com.google.protobuf.ByteString getMetaParamClass() {
    return metaParamClass_;
  }

  private void initFields() {
    className_ = com.google.protobuf.ByteString.EMPTY;
    metaParam_ = com.google.protobuf.ByteString.EMPTY;
    metaParamClass_ = com.google.protobuf.ByteString.EMPTY;
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized != -1) return isInitialized == 1;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeBytes(1, className_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeBytes(2, metaParam_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      output.writeBytes(3, metaParamClass_);
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, className_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, metaParam_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(3, metaParamClass_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  public static util.dconcurrent.core.DObject parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static util.dconcurrent.core.DObject parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static util.dconcurrent.core.DObject parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static util.dconcurrent.core.DObject parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static util.dconcurrent.core.DObject parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static util.dconcurrent.core.DObject parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static util.dconcurrent.core.DObject parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static util.dconcurrent.core.DObject parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static util.dconcurrent.core.DObject parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static util.dconcurrent.core.DObject parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(util.dconcurrent.core.DObject prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code dconcurrent.DObject}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder>
     implements util.dconcurrent.core.DObjectOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return util.dconcurrent.core.DConcurrent.internal_static_dconcurrent_DObject_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return util.dconcurrent.core.DConcurrent.internal_static_dconcurrent_DObject_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              util.dconcurrent.core.DObject.class, util.dconcurrent.core.DObject.Builder.class);
    }

    // Construct using util.dconcurrent.core.DObject.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      className_ = com.google.protobuf.ByteString.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      metaParam_ = com.google.protobuf.ByteString.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      metaParamClass_ = com.google.protobuf.ByteString.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return util.dconcurrent.core.DConcurrent.internal_static_dconcurrent_DObject_descriptor;
    }

    public util.dconcurrent.core.DObject getDefaultInstanceForType() {
      return util.dconcurrent.core.DObject.getDefaultInstance();
    }

    public util.dconcurrent.core.DObject build() {
      util.dconcurrent.core.DObject result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public util.dconcurrent.core.DObject buildPartial() {
      util.dconcurrent.core.DObject result = new util.dconcurrent.core.DObject(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.className_ = className_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      result.metaParam_ = metaParam_;
      if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
        to_bitField0_ |= 0x00000004;
      }
      result.metaParamClass_ = metaParamClass_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof util.dconcurrent.core.DObject) {
        return mergeFrom((util.dconcurrent.core.DObject)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(util.dconcurrent.core.DObject other) {
      if (other == util.dconcurrent.core.DObject.getDefaultInstance()) return this;
      if (other.hasClassName()) {
        setClassName(other.getClassName());
      }
      if (other.hasMetaParam()) {
        setMetaParam(other.getMetaParam());
      }
      if (other.hasMetaParamClass()) {
        setMetaParamClass(other.getMetaParamClass());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      util.dconcurrent.core.DObject parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (util.dconcurrent.core.DObject) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    // optional bytes className = 1;
    private com.google.protobuf.ByteString className_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>optional bytes className = 1;</code>
     */
    public boolean hasClassName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional bytes className = 1;</code>
     */
    public com.google.protobuf.ByteString getClassName() {
      return className_;
    }
    /**
     * <code>optional bytes className = 1;</code>
     */
    public Builder setClassName(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      className_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bytes className = 1;</code>
     */
    public Builder clearClassName() {
      bitField0_ = (bitField0_ & ~0x00000001);
      className_ = getDefaultInstance().getClassName();
      onChanged();
      return this;
    }

    // optional bytes metaParam = 2;
    private com.google.protobuf.ByteString metaParam_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>optional bytes metaParam = 2;</code>
     */
    public boolean hasMetaParam() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bytes metaParam = 2;</code>
     */
    public com.google.protobuf.ByteString getMetaParam() {
      return metaParam_;
    }
    /**
     * <code>optional bytes metaParam = 2;</code>
     */
    public Builder setMetaParam(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      metaParam_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bytes metaParam = 2;</code>
     */
    public Builder clearMetaParam() {
      bitField0_ = (bitField0_ & ~0x00000002);
      metaParam_ = getDefaultInstance().getMetaParam();
      onChanged();
      return this;
    }

    // optional bytes metaParamClass = 3;
    private com.google.protobuf.ByteString metaParamClass_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>optional bytes metaParamClass = 3;</code>
     */
    public boolean hasMetaParamClass() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional bytes metaParamClass = 3;</code>
     */
    public com.google.protobuf.ByteString getMetaParamClass() {
      return metaParamClass_;
    }
    /**
     * <code>optional bytes metaParamClass = 3;</code>
     */
    public Builder setMetaParamClass(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      metaParamClass_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bytes metaParamClass = 3;</code>
     */
    public Builder clearMetaParamClass() {
      bitField0_ = (bitField0_ & ~0x00000004);
      metaParamClass_ = getDefaultInstance().getMetaParamClass();
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:dconcurrent.DObject)
  }

  static {
    defaultInstance = new DObject(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:dconcurrent.DObject)
}

