// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: d-concurrent.proto

package util.dconcurrent.core;

public interface DObjectOrBuilder
    extends com.google.protobuf.MessageOrBuilder {

  // optional bytes className = 1;
  /**
   * <code>optional bytes className = 1;</code>
   */
  boolean hasClassName();
  /**
   * <code>optional bytes className = 1;</code>
   */
  com.google.protobuf.ByteString getClassName();

  // optional bytes metaParam = 2;
  /**
   * <code>optional bytes metaParam = 2;</code>
   */
  boolean hasMetaParam();
  /**
   * <code>optional bytes metaParam = 2;</code>
   */
  com.google.protobuf.ByteString getMetaParam();

  // optional bytes metaParamClass = 3;
  /**
   * <code>optional bytes metaParamClass = 3;</code>
   */
  boolean hasMetaParamClass();
  /**
   * <code>optional bytes metaParamClass = 3;</code>
   */
  com.google.protobuf.ByteString getMetaParamClass();
}
