// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: d-concurrent.proto

package util.dconcurrent.core;

public interface DStatusOrBuilder
    extends com.google.protobuf.MessageOrBuilder {

  // optional int32 runCount = 1;
  /**
   * <code>optional int32 runCount = 1;</code>
   */
  boolean hasRunCount();
  /**
   * <code>optional int32 runCount = 1;</code>
   */
  int getRunCount();

  // optional int32 callCount = 2;
  /**
   * <code>optional int32 callCount = 2;</code>
   */
  boolean hasCallCount();
  /**
   * <code>optional int32 callCount = 2;</code>
   */
  int getCallCount();
}
