// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: d-concurrent.proto

package io.grpc.distribute.core;

public final class DConcurrent {
  private DConcurrent() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dconcurrent_DObject_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dconcurrent_DObject_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dconcurrent_DStatus_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dconcurrent_DStatus_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\022d-concurrent.proto\022\013dconcurrent\032\031googl" +
      "e/protobuf/any.proto\"\211\001\n\007DObject\022\'\n\tclas" +
      "sName\030\001 \001(\0132\024.google.protobuf.Any\022\'\n\tmet" +
      "aParam\030\002 \001(\0132\024.google.protobuf.Any\022,\n\016me" +
      "taParamClass\030\003 \001(\0132\024.google.protobuf.Any" +
      "\".\n\007DStatus\022\020\n\010runCount\030\001 \001(\005\022\021\n\tcallCou" +
      "nt\030\002 \001(\0052\362\001\n\021DConcurrentServer\0229\n\tResetS" +
      "tat\022\024.dconcurrent.DStatus\032\024.google.proto" +
      "buf.Any\"\000\0227\n\007GetStat\022\024.google.protobuf.A" +
      "ny\032\024.dconcurrent.DStatus\"\000\0223\n\003Run\022\024.dcon",
      "current.DObject\032\024.dconcurrent.DObject\"\000\022" +
      "4\n\004Call\022\024.dconcurrent.DObject\032\024.dconcurr" +
      "ent.DObject\"\000B)\n\022io.grpc.distributeB\013DCo" +
      "ncurrentP\001\242\002\003LZZb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
        }, assigner);
    internal_static_dconcurrent_DObject_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_dconcurrent_DObject_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dconcurrent_DObject_descriptor,
        new String[] { "ClassName", "MetaParam", "MetaParamClass", });
    internal_static_dconcurrent_DStatus_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_dconcurrent_DStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dconcurrent_DStatus_descriptor,
        new String[] { "RunCount", "CallCount", });
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
