// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: d-concurrent.proto

package io.grpc.distribute.core;

public interface DObjectOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dconcurrent.DObject)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.google.protobuf.Any className = 1;</code>
   */
  boolean hasClassName();
  /**
   * <code>.google.protobuf.Any className = 1;</code>
   */
  com.google.protobuf.Any getClassName();
  /**
   * <code>.google.protobuf.Any className = 1;</code>
   */
  com.google.protobuf.AnyOrBuilder getClassNameOrBuilder();

  /**
   * <code>.google.protobuf.Any metaParam = 2;</code>
   */
  boolean hasMetaParam();
  /**
   * <code>.google.protobuf.Any metaParam = 2;</code>
   */
  com.google.protobuf.Any getMetaParam();
  /**
   * <code>.google.protobuf.Any metaParam = 2;</code>
   */
  com.google.protobuf.AnyOrBuilder getMetaParamOrBuilder();

  /**
   * <code>.google.protobuf.Any metaParamClass = 3;</code>
   */
  boolean hasMetaParamClass();
  /**
   * <code>.google.protobuf.Any metaParamClass = 3;</code>
   */
  com.google.protobuf.Any getMetaParamClass();
  /**
   * <code>.google.protobuf.Any metaParamClass = 3;</code>
   */
  com.google.protobuf.AnyOrBuilder getMetaParamClassOrBuilder();
}
