// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: d-concurrent.proto

package io.grpc.distribute.core;

/**
 * Protobuf type {@code dconcurrent.DStatus}
 */
public  final class DStatus extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:dconcurrent.DStatus)
    DStatusOrBuilder {
  // Use DStatus.newBuilder() to construct.
  private DStatus(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DStatus() {
    runCount_ = 0;
    callCount_ = 0;
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private DStatus(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            runCount_ = input.readInt32();
            break;
          }
          case 16: {

            callCount_ = input.readInt32();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return DConcurrent.internal_static_dconcurrent_DStatus_descriptor;
  }

  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return DConcurrent.internal_static_dconcurrent_DStatus_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            DStatus.class, Builder.class);
  }

  public static final int RUNCOUNT_FIELD_NUMBER = 1;
  private int runCount_;
  /**
   * <code>int32 runCount = 1;</code>
   */
  public int getRunCount() {
    return runCount_;
  }

  public static final int CALLCOUNT_FIELD_NUMBER = 2;
  private int callCount_;
  /**
   * <code>int32 callCount = 2;</code>
   */
  public int getCallCount() {
    return callCount_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (runCount_ != 0) {
      output.writeInt32(1, runCount_);
    }
    if (callCount_ != 0) {
      output.writeInt32(2, callCount_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (runCount_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, runCount_);
    }
    if (callCount_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, callCount_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof DStatus)) {
      return super.equals(obj);
    }
    DStatus other = (DStatus) obj;

    boolean result = true;
    result = result && (getRunCount()
        == other.getRunCount());
    result = result && (getCallCount()
        == other.getCallCount());
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + RUNCOUNT_FIELD_NUMBER;
    hash = (53 * hash) + getRunCount();
    hash = (37 * hash) + CALLCOUNT_FIELD_NUMBER;
    hash = (53 * hash) + getCallCount();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static DStatus parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static DStatus parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static DStatus parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static DStatus parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static DStatus parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static DStatus parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static DStatus parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static DStatus parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static DStatus parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static DStatus parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static DStatus parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static DStatus parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(DStatus prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code dconcurrent.DStatus}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:dconcurrent.DStatus)
          DStatusOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return DConcurrent.internal_static_dconcurrent_DStatus_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return DConcurrent.internal_static_dconcurrent_DStatus_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              DStatus.class, Builder.class);
    }

    // Construct using io.grpc.distribute.DStatus.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      runCount_ = 0;

      callCount_ = 0;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return DConcurrent.internal_static_dconcurrent_DStatus_descriptor;
    }

    public DStatus getDefaultInstanceForType() {
      return DStatus.getDefaultInstance();
    }

    public DStatus build() {
      DStatus result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public DStatus buildPartial() {
      DStatus result = new DStatus(this);
      result.runCount_ = runCount_;
      result.callCount_ = callCount_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof DStatus) {
        return mergeFrom((DStatus)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(DStatus other) {
      if (other == DStatus.getDefaultInstance()) return this;
      if (other.getRunCount() != 0) {
        setRunCount(other.getRunCount());
      }
      if (other.getCallCount() != 0) {
        setCallCount(other.getCallCount());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      DStatus parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (DStatus) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int runCount_ ;
    /**
     * <code>int32 runCount = 1;</code>
     */
    public int getRunCount() {
      return runCount_;
    }
    /**
     * <code>int32 runCount = 1;</code>
     */
    public Builder setRunCount(int value) {
      
      runCount_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 runCount = 1;</code>
     */
    public Builder clearRunCount() {
      
      runCount_ = 0;
      onChanged();
      return this;
    }

    private int callCount_ ;
    /**
     * <code>int32 callCount = 2;</code>
     */
    public int getCallCount() {
      return callCount_;
    }
    /**
     * <code>int32 callCount = 2;</code>
     */
    public Builder setCallCount(int value) {
      
      callCount_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 callCount = 2;</code>
     */
    public Builder clearCallCount() {
      
      callCount_ = 0;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:dconcurrent.DStatus)
  }

  // @@protoc_insertion_point(class_scope:dconcurrent.DStatus)
  private static final DStatus DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new DStatus();
  }

  public static DStatus getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DStatus>
      PARSER = new com.google.protobuf.AbstractParser<DStatus>() {
    public DStatus parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new DStatus(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<DStatus> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<DStatus> getParserForType() {
    return PARSER;
  }

  public DStatus getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

