// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: d-concurrent.proto

package io.grpc.distribute.core;

public interface DStatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dconcurrent.DStatus)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 runCount = 1;</code>
   */
  int getRunCount();

  /**
   * <code>int32 callCount = 2;</code>
   */
  int getCallCount();
}
